name: Test exit code
run-name: ${{ github.actor }} is testing out exit code
on: [push]
jobs:
  Generate_exit_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run python script
        id:   exit_code_generator
        run:  |
          python exit_code.py

      - name: Catch exit code
        if:   always() && steps.exit_code_generator.outcome == 'failure'
        run:  |
          echo 'send message'