name: Testing actions
run-name: ${{ github.actor }} is testing out actions
on: 
  # push:
  pull_request:

permissions:
  contents: write
    
jobs:
  Label_and_sem_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Get label name
        id: label_name
        if: contains( github.event.pull_request.labels.*.name, 'buggg')
        run: echo "test"


      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: v${{ steps.semvers.outputs.patch }}
      #     release_name: v${{ steps.semvers.outputs.patch }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false

      # - name: test
      #   run: | 
      #     echo ${{ steps.semvers.outputs.major }}
      #     echo ${{ steps.semvers.outputs.minor }}
      #     echo ${{ steps.semvers.outputs.patch }}
      #     echo ${{ steps.semvers.outputs.v_major }}
      #     echo ${{ steps.semvers.outputs.v_minor }}
      #     echo ${{ steps.semvers.outputs.v_patch }}

      # - name: Get branch name
      #   run: echo "branch=${GITHUB_REF#refs/heads/}"

      # - name: Get branch name
      #   run: echo "${GITHUB_HEAD_REF##*/}"

      # - name: Get pr name
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: echo "$PR_NUMBER"

  # Generate_exit_code:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Check out repository code
  #         uses: actions/checkout@v4
          
      # - name: Run python script
      #   id:   exit_code_generator
      #   continue-on-error: true
      #   run:  |
      #     python exit_code.py

      # - name: Catch exit code
      #   if:   always() && steps.exit_code_generator.outcome == 'failure'
      #   env:
      #     WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAqt2tvNo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=xc_gcoYN9mOqSJBlG3CaWv50uZj8ZNtm5ZQ_Bhl992Q
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' -d \
      #     '{"text": "GitHub Actions Airbyte Freshness Test Failed\n \
      #     Run URL: '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'\n \
      #     See results in Redash: https://redash.tools.improvado.io/embed/query/9441/visualization/10947?api_key=8K0KW0F3lLhcfq2QyfGCVTQbBmpz01q22lWmdPdc&"}' \
      #     $WEBHOOK_URL
