name: Test exit code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Generate_exit_code:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python exit_code.py