name: main wf
on:
  workflow_dispatch:
    inputs:
      some:
        type: choice
        default: none
        options: 
          - none
          - one
          - two
  pull_request:
  # - push

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: file creation
        run: |
          echo 123 > test1
          echo 321 > test2

      - name: save files to repo
        uses: stefanzweifel/git-auto-commit-action@v5
            
