name: main wf
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test-step1
        run: echo "github.event_name"
    
      - name: test-step2
        if: github.event_name != 'release'
        run: echo 'not a release'
    
  # call_local_wf:
  #   uses: ./.github/workflows/action.yml
  #   with:
  #     secretly_secret: ${{ needs.set_envs.outputs.ps }}
  #     secretly_secret_string: "passing a secret ${{ needs.set_envs.outputs.ps }}"
  #     # some: true
