name: main wf
on:
  push

jobs:
  call_local_wf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call local wf
        uses: ./.github/workflow/sub_wf.yml
      - run: echo 'Done'
