name: main wf
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: action test
        uses: actions/test_action.yml@v1
        with:
          my_int: 100
          my_dict: |
            {
              'dpth': 100,
              'ref_from': 'none'
            }
    
  # call_local_wf:
  #   uses: ./.github/workflows/action.yml
  #   with:
  #     secretly_secret: ${{ needs.set_envs.outputs.ps }}
  #     secretly_secret_string: "passing a secret ${{ needs.set_envs.outputs.ps }}"
  #     # some: true
