name: main wf
on:
  - workflow_dispatch
  - pull_request
  - push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  call_local_wf:
    uses: ./.github/workflows/action.yml
    # with:
    #   secretly_secret: ${{ needs.set_envs.outputs.ps }}
    #   secretly_secret_string: "passing a secret ${{ needs.set_envs.outputs.ps }}"
      # some: true

      # - name: Get run attempt number
      #   run: |
      #     if [[ ${{ github.run_attempt }} == 1 ]];
      #       then
      #         echo 1
      #       else
      #         echo ${{ github.run_attempt }}
      #     fi
            
      
      # - name: action test
      #   uses: ./.github/actions
      #   with:
      #     my_int: 100
      #     my_dict: |
      #       {
      #         'dpth': 100,
      #         'ref_from': 'master'
      #       }
    
