name: main wf
on:
  workflow_dispatch:
    inputs:
      some:
        type: choice
        default: none
        options: 
          - none
          - one
          - two
  pull_request:
  push:

permissions:
      contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: file creation
        run: |
          echo wrongone > manifest.json
          mkdir target
          echo rightone > target/manifest.json

      - name: save files to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'target/manifest.json'
            
