name: main wf
on:
  workflow_dispatch:
    inputs:
      some:
        type: choice
        default: none
        options: 
          - none
          - one
          - two
  pull_request:
  # - push

jobs:
  before_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for differences
        run: |
          git fetch origin
          git diff origin/${{ github.head_ref }} origin/master --exit-code --quiet && echo 'Branch is not up-to-date with main' || echo 'The branch is up-to-date'
          # # echo $?
          # if [[ $? == 1 ]];
          #   then
          #     echo 'Branch is not up-to-date with main'
          #     # exit $?
          #   else
          #     echo 'The branch is up-to-date'
          # fi

      # - name: some
      #   run: |
      #     echo ${{ inputs.some }}; echo ${{ inputs.some == 'none' }}; echo ${{ ! inputs.some == 'none' }}; echo ${{ github.actor }};
      #     echo ${{ github.actor_id }}

  test:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["oleggur", "technomonah", "Solovechik1"]'), github.actor)
    # if: ${{ inputs.some != 'none' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: comp
        run: |
          if [[ ${{ inputs.some }} == 'one' ]]; then
            echo 'first case'
          elif [[ ${{ inputs.some }} == 'one' ]]; then
            echo 'second case'
          elif [[ ${{ inputs.some }} == "one" ]]; then
            echo 'third case'
          elif [[ ${{ inputs.some }} == '' ]]; then
            echo 'forth case'
          fi
            
  # call_local_wf:
  #   uses: ./.github/workflows/action.yml
    # with:
    #   secretly_secret: ${{ needs.set_envs.outputs.ps }}
    #   secretly_secret_string: "passing a secret ${{ needs.set_envs.outputs.ps }}"
      # some: true

      # - name: Get run attempt number
      #   run: |
      #     if [[ ${{ github.run_attempt }} == 1 ]];
      #       then
      #         echo 1
      #       else
      #         echo ${{ github.run_attempt }}
      #     fi
            
      
      # - name: action test
      #   uses: ./.github/actions
      #   with:
      #     my_int: 100
      #     my_dict: |
      #       {
      #         'dpth': 100,
      #         'ref_from': 'master'
      #       }
    
