name: main wf
on:
  # push
  workflow_dispatch

jobs:
  # test:
  #   env:
  #     cond: false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: any
  #       if: ${{ fromJSON(env.cond) }}
  #       uses: docker/setup-buildx-action@v3
  call_local_wf:
    uses: ./.github/workflows/action.yml
    with:
      secretly_secret: |
        passing a secret ${{ secrets.TEST }}
      # some: true

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: some
  #       run: echo ${{ github.ref }}
