name: main wf
on:
  workflow_dispatch

jobs:
  call_local_wf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call local wf
        uses: ./action.yml
      - run: echo 'Done'
