name: main wf
on:
  # push
  workflow_dispatch

env:
  s: ${{ secrets.TEST }}

jobs:
  # test:
  #   env:
  #     cond: false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: any
  #       if: ${{ fromJSON(env.cond) }}
  #       uses: docker/setup-buildx-action@v3
  call_local_wf:
    uses: ./.github/workflows/action.yml
    with:
      secretly_secret: ${{ env.s }}
      secretly_secret_string: "passing a secret ${{ env.s }}"
      # some: true

  test:
    name: hash_test
    runs-on: ubuntu-latest
    steps:
      - name: to_file1
        run: echo ${{ env.s }} > file1

      - name: from_file1
        run: echo "${{ hashFiles('file1') }}"

      - name: to_file2
        run: echo "passing a secret ${{ env.s }}" > file2

      - name: from_file2
        run: echo "${{ hashFiles('file2') }}"

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: some
  #       run: echo ${{ github.ref }}
